
import dbConnect from '../lib/db/mongodb';
import User from '../models/User';
import Application from '../models/Application';
import Job from '../models/Job';

// Polyfill for models if they rely on being registered by Next.js API routes
// (Imports above should handle it if they export the model)

async function checkData() {
    console.log('Connecting to DB...');
    await dbConnect();
    console.log('Connected.');

    const userCount = await User.countDocuments();
    console.log(`Total Users: ${userCount}`);

    const jobCount = await Job.countDocuments();
    console.log(`Total Jobs: ${jobCount}`);

    const appCount = await Application.countDocuments();
    console.log(`Total Applications: ${appCount}`);

    if (appCount > 0) {
        const apps = await Application.find().limit(5).lean();
        console.log('Sample Applications:');
        apps.forEach(app => {
            console.log({
                id: app._id,
                applicant: app.applicant,
                job: app.job,
                status: app.status
            });
            console.log('Applicant Type:', typeof app.applicant);
        });
    } else {
        console.log('No applications found.');
    }

    // List all users and their application counts
    const users = await User.find({}, 'name email role').lean();
    console.log('--- User Applications Audit ---');
    for (const u of users) {
        const count = await Application.countDocuments({ applicant: u._id });
        console.log(`User: ${u.email} (${u.role}) - Applications: ${count}`);

        // Seed data for the first job seeker if they have 0
        if (u.role === 'job_seeker' && count === 0) {
            console.log(`Seeding mock application for ${u.email}...`);
            const job = await Job.findOne({ status: 'active' });
            if (job) {
                try {
                    await Application.create({
                        job: job._id,
                        applicant: u._id,
                        cvUrl: 'https://example.com/cv.pdf',
                        coverLetter: 'Mock application generated by debug script',
                        status: 'pending'
                    });
                    console.log('Seeded successfully.');
                } catch (e) {
                    console.error('Failed to seed:', e);
                }
            } else {
                console.log('No active job found to apply to.');
            }
        }
    }

    // Check a sample user
    const user = await User.findOne().lean() as any;
    if (user) {
        console.log('Sample User ID:', user._id);
        // types check
        const appsForUser = await Application.find({ applicant: user._id });
        console.log(`Applications for sample user (${user._id}): ${appsForUser.length}`);
    }

    process.exit(0);
}

checkData().catch(console.error);
